services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - monitoring-net
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=iot_db
      - DB_USER=iot_user
      - DB_PASS=iot_password

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - monitoring-net

  sensor:
    build: ./sensor_simulator
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/data
    networks:
      - monitoring-net

volumes:
  db_data:

networks:
  monitoring-net:
    driver: bridge
