version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - monitoring-net

  sensor:
    build: ./sensor_simulator
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/data
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
